# Параметры модели
repo_id: "cvssp/audioldm-s-full-v2"
device: "cuda"
cache_dir: "model_cache"

# Параметры генерации
prompt: "Clear Techno music with a strong, upbeat tempo"
audio_length_in_s: 3.0
num_inference_steps: 50

# Параметры водяного знака
n_bits: 35           # длина водяного знака
epsilon: 0.1         # минимальный зазор
lambda_wm: 1.0       # вес водяного лосса
lambda_qual: 150.0   # вес лосса качества

# Параметры оптимизации
optimization_steps: 100   # количество шагов
lr: 0.01
target_length: 48000      # 3 сек * 16000 Гц

# Параметры путей
output_dir: "output_watermarked"
keys_dir: "watermark_keys"